os:
	- linux
sudo: false
addons:
	apt:
		# Flutter depends upon /usr/lib/x866/ version
		sources:
			- ubuntu-toolchain-r-test # if we don't speciy
		packages:
			- libstdc++6
			- fonts-droid-fallback
before_script:
	- git clone https://github.com/flutter/flutter.git -b beta
	- ./flutter/bin/flutter doctor
script:
	- ./flutter/bin/flutter test
cache:
	directories:
		- $HOME/.pub-cache

